services: 
  php-app: 
    build: 
      context: . 
      dockerfile: Dockerfile.php
    ports: 
      - "8082:80" 
    depends_on:
      - mariadb
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  mariadb: 
    build: 
      context: .
      dockerfile: Dockerfile.db
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: bulletin_board
    ports: 
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
